# Generated by Django 5.0.6 on 2024-06-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='capabilities',
            field=models.JSONField(default=dict),
        ),
    ]
