# Generated by Django 5.0.6 on 2024-06-11 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_bike_capabilities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='is_in_use',
        ),
        migrations.AddField(
            model_name='bike',
            name='reserved_by',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
