# Generated by Django 5.0.6 on 2024-06-11 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0003_remove_bike_is_in_use_bike_reserved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='reserved_by',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
