# Generated by Django 5.0.6 on 2024-06-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0004_alter_bike_reserved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='notes',
            field=models.CharField(default='Geen notities', max_length=400),
        ),
    ]
