# Generated by Django 5.0.6 on 2024-06-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0005_bike_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='total_rides',
            field=models.IntegerField(default=0),
        ),
    ]
