# Generated by Django 5.0.6 on 2024-06-15 17:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0006_bike_total_rides'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('start_latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('start_longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('end_latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('end_longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('distance', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('duration', models.DurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.bike')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
