# Generated by Django 5.0.6 on 2024-06-11 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userdetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='reserved_bike',
        ),
    ]
